openapi: 3.1.0
info:
  title: SaliteMihret Reporting API
  version: 1.0.0
servers:
  - url: https://salitemihret.local/api
paths:
  /reports:
    get:
      summary: List available reports
      operationId: listReports
      responses:
        '200':
          description: Report definitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReportDefinition'
  /reports/{reportId}/run:
    post:
      summary: Execute report with filters
      operationId: runReport
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: Report result dataset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResult'
  /reports/{reportId}/schedule:
    post:
      summary: Configure scheduled delivery
      operationId: scheduleReport
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportScheduleInput'
      responses:
        '202':
          description: Schedule updated
components:
  schemas:
    ReportDefinition:
      type: object
      required:
        - id
        - domain
        - title
      properties:
        id:
          type: string
        domain:
          type: string
        title:
          type: string
        description:
          type: string
        supportsScheduling:
          type: boolean
    ReportResult:
      type: object
      required:
        - columns
        - rows
      properties:
        columns:
          type: array
          items:
            type: string
        rows:
          type: array
          items:
            type: array
            items:
              type: string
    ReportScheduleInput:
      type: object
      required:
        - cron
        - deliveryChannels
      properties:
        cron:
          type: string
        deliveryChannels:
          type: array
          items:
            type: string
        recipients:
          type: array
          items:
            type: string
