"""stabilize abenet enrollment types and indexes (auto-generated stub)

Revision ID: 63ecdf8616e7
Revises: e1a5c2e7c4a4
Create Date: 2025-11-28 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63ecdf8616e7'
down_revision = 'e1a5c2e7c4a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abenet_enrollments', 'parent_member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('abenet_enrollments', 'child_first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('abenet_enrollments', 'child_last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('abenet_enrollments', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column(
        'abenet_enrollments',
        'service_stage',
        existing_type=sa.VARCHAR(length=80),
        type_=sa.Enum('Alphabet', 'Reading', 'ForDeacons', name='abenet_service_stage'),
        nullable=False,
        postgresql_using="service_stage::abenet_service_stage"
    )
    # Normalize existing status values to the new enum before casting
    op.execute("UPDATE abenet_enrollments SET status = 'Active' WHERE status = 'Enrolled'")
    op.execute("UPDATE abenet_enrollments SET status = 'Paused' WHERE status = 'OnHold'")
    op.execute("UPDATE abenet_enrollments SET status = 'Cancelled' WHERE status = 'Withdrawn'")
    op.alter_column('abenet_enrollments', 'monthly_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    # Drop old default before type change
    op.execute("ALTER TABLE abenet_enrollments ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        'abenet_enrollments',
        'status',
        existing_type=postgresql.ENUM('Enrolled', 'OnHold', 'Completed', 'Withdrawn', 'Active', 'Paused', 'Cancelled', name='school_enrollment_status'),
        type_=sa.Enum('Active', 'Paused', 'Completed', 'Cancelled', name='abenet_enrollment_status'),
        existing_nullable=False,
        existing_server_default=sa.text("'Enrolled'::school_enrollment_status"),
        postgresql_using="status::text::abenet_enrollment_status",
        server_default=sa.text("'Active'::abenet_enrollment_status")
    )
    op.alter_column('abenet_enrollments', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_abenet_child_id', table_name='abenet_enrollments')
    op.drop_index('ix_abenet_enrollments_member_id', table_name='abenet_enrollments')
    op.drop_index('ix_abenet_enrollments_status', table_name='abenet_enrollments')
    op.drop_index('ix_abenet_parent_member_id', table_name='abenet_enrollments')
    op.drop_constraint('fk_abenet_parent_member', 'abenet_enrollments', type_='foreignkey')
    op.drop_constraint('fk_abenet_child_member', 'abenet_enrollments', type_='foreignkey')
    op.drop_constraint('abenet_enrollments_mentor_member_id_fkey', 'abenet_enrollments', type_='foreignkey')
    op.drop_constraint('abenet_enrollments_member_id_fkey', 'abenet_enrollments', type_='foreignkey')
    op.execute("UPDATE abenet_enrollments SET child_id = NULL WHERE child_id IS NOT NULL AND child_id NOT IN (SELECT id FROM children)")
    op.create_foreign_key(None, 'abenet_enrollments', 'children', ['child_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'abenet_enrollments', 'members', ['parent_member_id'], ['id'], ondelete='CASCADE')
    op.drop_column('abenet_enrollments', 'member_id')
    op.drop_column('abenet_enrollments', 'mentor_member_id')
    op.drop_column('abenet_enrollments', 'completion_date')
    op.drop_column('abenet_enrollments', 'cohort')
    op.drop_index('ix_lessons_level', table_name='lessons')
    op.create_index(op.f('ix_member_contribution_payments_member_id'), 'member_contribution_payments', ['member_id'], unique=False)
    op.execute("ALTER TABLE member_ministries DROP CONSTRAINT IF EXISTS uq_member_ministry")
    op.execute("ALTER TABLE member_ministries ADD CONSTRAINT uq_member_ministry UNIQUE (member_id, ministry_id)")
    op.execute("ALTER TABLE member_tags DROP CONSTRAINT IF EXISTS uq_member_tag")
    op.execute("ALTER TABLE member_tags ADD CONSTRAINT uq_member_tag UNIQUE (member_id, tag_id)")
    op.drop_index('ix_members_contribution_next_due_at', table_name='members')
    op.drop_index('ix_members_created_at', table_name='members')
    op.drop_index('ix_members_deleted_at', table_name='members')
    op.drop_index('ix_members_status', table_name='members')
    op.drop_index('ix_mezmur_category', table_name='mezmur')
    op.drop_index('ix_mezmur_language', table_name='mezmur')
    op.drop_index('ix_newcomers_arrival_date', table_name='newcomers')
    op.drop_index('ix_newcomers_status', table_name='newcomers')
    op.drop_index('ix_payments_posted_at', table_name='payments')
    op.alter_column('priests', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('priests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_sponsorships_sponsor', table_name='sponsorships')
    op.create_index(op.f('ix_sponsorships_beneficiary_member_id'), 'sponsorships', ['beneficiary_member_id'], unique=False)
    op.create_index(op.f('ix_sponsorships_newcomer_id'), 'sponsorships', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_sponsorships_sponsor_member_id'), 'sponsorships', ['sponsor_member_id'], unique=False)
    op.alter_column('sunday_school_enrollments', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='member_gender'),
               nullable=False)
    op.alter_column('sunday_school_enrollments', 'membership_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_sunday_school_enrollments_member_id', table_name='sunday_school_enrollments')
    op.drop_index('ix_sunday_school_member_username', table_name='sunday_school_enrollments')
    op.create_index(op.f('ix_sunday_school_enrollments_member_username'), 'sunday_school_enrollments', ['member_username'], unique=False)
    op.drop_index('ix_user_audit_logs_target', table_name='user_audit_logs')
    op.create_index(op.f('ix_user_audit_logs_target_user_id'), 'user_audit_logs', ['target_user_id'], unique=False)
    op.drop_index('ix_user_invitations_email', table_name='user_invitations')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_user_invitations_email', 'user_invitations', ['email'], unique=False)
    op.drop_index(op.f('ix_user_audit_logs_target_user_id'), table_name='user_audit_logs')
    op.create_index('ix_user_audit_logs_target', 'user_audit_logs', ['target_user_id'], unique=False)
    op.drop_index(op.f('ix_sunday_school_enrollments_member_username'), table_name='sunday_school_enrollments')
    op.create_index('ix_sunday_school_member_username', 'sunday_school_enrollments', ['member_username'], unique=False)
    op.create_index('ix_sunday_school_enrollments_member_id', 'sunday_school_enrollments', ['member_id'], unique=False)
    op.alter_column('sunday_school_enrollments', 'membership_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sunday_school_enrollments', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='member_gender'),
               nullable=True)
    op.drop_index(op.f('ix_sponsorships_sponsor_member_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_newcomer_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_beneficiary_member_id'), table_name='sponsorships')
    op.create_index('ix_sponsorships_sponsor', 'sponsorships', ['sponsor_member_id'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.alter_column('priests', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('priests', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index('ix_payments_posted_at', 'payments', ['posted_at'], unique=False)
    op.create_index('ix_newcomers_status', 'newcomers', ['status'], unique=False)
    op.create_index('ix_newcomers_arrival_date', 'newcomers', ['arrival_date'], unique=False)
    op.create_index('ix_mezmur_language', 'mezmur', ['language'], unique=False)
    op.create_index('ix_mezmur_category', 'mezmur', ['category'], unique=False)
    op.create_index('ix_members_status', 'members', ['status'], unique=False)
    op.create_index('ix_members_deleted_at', 'members', ['deleted_at'], unique=False)
    op.create_index('ix_members_created_at', 'members', ['created_at'], unique=False)
    op.create_index('ix_members_contribution_next_due_at', 'members', ['contribution_next_due_at'], unique=False)
    op.drop_constraint('uq_member_tag', 'member_tags', type_='unique')
    op.drop_constraint('uq_member_ministry', 'member_ministries', type_='unique')
    op.drop_index(op.f('ix_member_contribution_payments_member_id'), table_name='member_contribution_payments')
    op.create_index('ix_lessons_level', 'lessons', ['level'], unique=False)
    op.add_column('abenet_enrollments', sa.Column('cohort', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('abenet_enrollments', sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('abenet_enrollments', sa.Column('mentor_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('abenet_enrollments', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'abenet_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'abenet_enrollments', type_='foreignkey')
    op.create_foreign_key('abenet_enrollments_member_id_fkey', 'abenet_enrollments', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('abenet_enrollments_mentor_member_id_fkey', 'abenet_enrollments', 'members', ['mentor_member_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_abenet_child_member', 'abenet_enrollments', 'members', ['child_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_abenet_parent_member', 'abenet_enrollments', 'members', ['parent_member_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_abenet_parent_member_id', 'abenet_enrollments', ['parent_member_id'], unique=False)
    op.create_index('ix_abenet_enrollments_status', 'abenet_enrollments', ['status'], unique=False)
    op.create_index('ix_abenet_enrollments_member_id', 'abenet_enrollments', ['member_id'], unique=False)
    op.create_index('ix_abenet_child_id', 'abenet_enrollments', ['child_id'], unique=False)
    op.alter_column('abenet_enrollments', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('abenet_enrollments', 'status',
               existing_type=sa.Enum('Active', 'Paused', 'Completed', 'Cancelled', name='abenet_enrollment_status'),
               type_=postgresql.ENUM('Enrolled', 'OnHold', 'Completed', 'Withdrawn', 'Active', 'Paused', 'Cancelled', name='school_enrollment_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Enrolled'::school_enrollment_status"))
    op.alter_column('abenet_enrollments', 'monthly_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('abenet_enrollments', 'service_stage',
               existing_type=sa.Enum('Alphabet', 'Reading', 'ForDeacons', name='abenet_service_stage'),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('abenet_enrollments', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('abenet_enrollments', 'child_last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('abenet_enrollments', 'child_first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('abenet_enrollments', 'parent_member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
