export const LANGUAGE_OPTIONS = [
  { value: "Amharic", label: "Amharic" },
  { value: "Tigrinya", label: "Tigrinya" },
  { value: "Oromo", label: "Oromo" },
  { value: "Arabic", label: "Arabic" },
  { value: "English", label: "English" },
  { value: "French", label: "French" },
  { value: "Spanish", label: "Spanish" },
  { value: "Somali", label: "Somali" },
  { value: "Swahili", label: "Swahili" },
  { value: "Other", label: "Other" },
];

// ISO 3166-1 country and territory names used across dropdowns.
const COUNTRY_NAMES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czechia",
  "Cote d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Reunion",
  "Saint Barthelemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Aland Islands",
];

export const COUNTRY_OPTIONS = COUNTRY_NAMES.map((country) => ({
  value: country,
  label: country,
}));

export const PROVINCE_OPTIONS = [
  { value: "Alberta", label: "Alberta" },
  { value: "British Columbia", label: "British Columbia" },
  { value: "Manitoba", label: "Manitoba" },
  { value: "New Brunswick", label: "New Brunswick" },
  { value: "Newfoundland and Labrador", label: "Newfoundland and Labrador" },
  { value: "Nova Scotia", label: "Nova Scotia" },
  { value: "Ontario", label: "Ontario" },
  { value: "Prince Edward Island", label: "Prince Edward Island" },
  { value: "Quebec", label: "Quebec" },
  { value: "Saskatchewan", label: "Saskatchewan" },
  { value: "Northwest Territories", label: "Northwest Territories" },
  { value: "Nunavut", label: "Nunavut" },
  { value: "Yukon", label: "Yukon" },
  { value: "Other", label: "Other" },
];

export const CITY_OPTIONS_BY_PROVINCE: Record<string, Array<{ value: string; label: string }>> = {
  Alberta: [
    { value: "Calgary", label: "Calgary" },
    { value: "Edmonton", label: "Edmonton" },
    { value: "Red Deer", label: "Red Deer" },
    { value: "Lethbridge", label: "Lethbridge" },
    { value: "Fort McMurray", label: "Fort McMurray" },
  ],
  "British Columbia": [
    { value: "Vancouver", label: "Vancouver" },
    { value: "Surrey", label: "Surrey" },
    { value: "Burnaby", label: "Burnaby" },
    { value: "Victoria", label: "Victoria" },
    { value: "Kelowna", label: "Kelowna" },
  ],
  Manitoba: [
    { value: "Winnipeg", label: "Winnipeg" },
    { value: "Brandon", label: "Brandon" },
    { value: "Steinbach", label: "Steinbach" },
    { value: "Thompson", label: "Thompson" },
    { value: "Portage la Prairie", label: "Portage la Prairie" },
  ],
  "New Brunswick": [
    { value: "Moncton", label: "Moncton" },
    { value: "Saint John", label: "Saint John" },
    { value: "Fredericton", label: "Fredericton" },
    { value: "Miramichi", label: "Miramichi" },
    { value: "Bathurst", label: "Bathurst" },
  ],
  "Newfoundland and Labrador": [
    { value: "St. John's", label: "St. John's" },
    { value: "Mount Pearl", label: "Mount Pearl" },
    { value: "Corner Brook", label: "Corner Brook" },
    { value: "Gander", label: "Gander" },
    { value: "Happy Valley-Goose Bay", label: "Happy Valley-Goose Bay" },
  ],
  "Nova Scotia": [
    { value: "Halifax", label: "Halifax" },
    { value: "Sydney", label: "Sydney" },
    { value: "Dartmouth", label: "Dartmouth" },
    { value: "Truro", label: "Truro" },
    { value: "New Glasgow", label: "New Glasgow" },
  ],
  Ontario: [
    { value: "Toronto", label: "Toronto" },
    { value: "Ottawa", label: "Ottawa" },
    { value: "Mississauga", label: "Mississauga" },
    { value: "Brampton", label: "Brampton" },
    { value: "Hamilton", label: "Hamilton" },
  ],
  "Prince Edward Island": [
    { value: "Charlottetown", label: "Charlottetown" },
    { value: "Summerside", label: "Summerside" },
    { value: "Stratford", label: "Stratford" },
    { value: "Cornwall", label: "Cornwall" },
    { value: "Montague", label: "Montague" },
  ],
  Quebec: [
    { value: "Montreal", label: "Montreal" },
    { value: "Quebec City", label: "Quebec City" },
    { value: "Laval", label: "Laval" },
    { value: "Gatineau", label: "Gatineau" },
    { value: "Longueuil", label: "Longueuil" },
  ],
  Saskatchewan: [
    { value: "Saskatoon", label: "Saskatoon" },
    { value: "Regina", label: "Regina" },
    { value: "Prince Albert", label: "Prince Albert" },
    { value: "Moose Jaw", label: "Moose Jaw" },
    { value: "Swift Current", label: "Swift Current" },
  ],
  "Northwest Territories": [
    { value: "Yellowknife", label: "Yellowknife" },
    { value: "Hay River", label: "Hay River" },
    { value: "Inuvik", label: "Inuvik" },
    { value: "Fort Smith", label: "Fort Smith" },
    { value: "Behchoko", label: "Behchoko" },
  ],
  Nunavut: [
    { value: "Iqaluit", label: "Iqaluit" },
    { value: "Rankin Inlet", label: "Rankin Inlet" },
    { value: "Arviat", label: "Arviat" },
    { value: "Baker Lake", label: "Baker Lake" },
    { value: "Cambridge Bay", label: "Cambridge Bay" },
  ],
  Yukon: [
    { value: "Whitehorse", label: "Whitehorse" },
    { value: "Dawson City", label: "Dawson City" },
    { value: "Watson Lake", label: "Watson Lake" },
    { value: "Haines Junction", label: "Haines Junction" },
    { value: "Carmacks", label: "Carmacks" },
  ],
  Other: [],
};

export const COUNTY_OPTIONS = [
  { value: "Edmonton", label: "Edmonton" },
  { value: "Calgary", label: "Calgary" },
  { value: "Red Deer", label: "Red Deer" },
  { value: "Lethbridge", label: "Lethbridge" },
  { value: "Fort McMurray", label: "Fort McMurray" },
  { value: "Grande Prairie", label: "Grande Prairie" },
  { value: "St. Albert", label: "St. Albert" },
  { value: "Sherwood Park", label: "Sherwood Park" },
  { value: "Spruce Grove", label: "Spruce Grove" },
  { value: "Fort Saskatchewan", label: "Fort Saskatchewan" },
  { value: "Other", label: "Other" },
];

export const SPONSORSHIP_PROGRAM_OPTIONS = [
  { value: "Education", label: "Education" },
  { value: "Nutrition", label: "Nutrition" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Housing", label: "Housing" },
  { value: "EmergencyRelief", label: "Emergency Relief" },
  { value: "SpecialProjects", label: "Special Projects" },
  { value: "Youth Scholarship", label: "Youth Scholarship" },
];

export const SPONSORSHIP_FREQUENCY_OPTIONS = [
  { value: "OneTime", label: "One-time" },
  { value: "Monthly", label: "Monthly" },
  { value: "Quarterly", label: "Quarterly" },
  { value: "Yearly", label: "Yearly" },
];

export const SPONSORSHIP_PLEDGE_CHANNEL_OPTIONS = [
  { value: "InPerson", label: "In person" },
  { value: "OnlinePortal", label: "Online portal" },
  { value: "Phone", label: "Phone" },
  { value: "EventBooth", label: "Event booth" },
];

export const SPONSORSHIP_REMINDER_CHANNEL_OPTIONS = [
  { value: "Email", label: "Email" },
  { value: "SMS", label: "SMS" },
  { value: "Phone", label: "Phone" },
  { value: "WhatsApp", label: "WhatsApp" },
];

export const SPONSORSHIP_MOTIVATION_OPTIONS = [
  { value: "HonorMemorial", label: "Honor / Memorial" },
  { value: "CommunityOutreach", label: "Community outreach" },
  { value: "Corporate", label: "Corporate" },
  { value: "ParishInitiative", label: "Parish initiative" },
  { value: "Other", label: "Other" },
];

export const VOLUNTEER_SERVICE_OPTIONS = [
  { value: "HolyDayCleanup", label: "Holy Day cleanup" },
  { value: "MealSupport", label: "Meal support" },
  { value: "GeneralService", label: "General service" },
  { value: "CommunityOutreach", label: "Community outreach" },
  { value: "YouthMentoring", label: "Youth mentoring" },
];

export const VOLUNTEER_TYPE_OPTIONS = [
  { value: "Holiday", label: "Holiday" },
  { value: "GeneralService", label: "General service" },
];

export const MEMBER_STATUS_OPTIONS = [
  { value: "Active", label: "Active" },
  { value: "Pending", label: "Pending" },
  { value: "Inactive", label: "Inactive" },
  { value: "Archived", label: "Archived" },
];
